### ISSUE TITLE
release

### ISSUE THREAD

**Issue by dbu** [thephpleague/flysystem-phpcr#1]
@frankdejonge thanks for your talk last week. i wanted to see this in action and did the phpcr implementation. now i have a couple of questions:

* I was expecting a generic base test that ensures the behaviour of every interface method is consistent. but i only found specific tests. did i not look in the right place or does that not exist?
* Is there an exact specification which keys should be in the returned arrays? Could we improve the phpdoc on that aspect - portability is an illusion if the returned information is different for each storage adapter...
* Is there a way to contribute this repository to the 'league?

**Comment by frankdejonge** [comment]
Hi @dbu!

There's wiki page which can help you out in the process: https://github.com/thephpleague/flysystem/wiki/Adapter-Internals. This will explain much of the logic behind the design. Since there haven't been many people other than me creating the adapters (3 others I think) not much time was spent on this.

There's indeed no standard test suite, but that looks like a great idea to create and share amongst the adapters.

Once your adapter is ready, you can transfer the adapter to the `thephpleague` account after which I can add you as the package maintainer.

**Comment by dbu** [comment]
@frankdejonge okay, i think this is ready for a first throw :-)

i tried to "transfer" the repository to thephpleague but got the error "You don't have admin rights to thephpleague" - is there a different place where i can do this? i added you as "collaborator" but i doubt this allows you to move the repo.

worst case you can just create the repo in thephpleague account and give me rights on it and i git push there. we would only lose the two github issues which is not a problem imho.

**Comment by frankdejonge** [comment]
@dbu Hi, don't know if you got my tweet, but I need admin right to move this repo. Could you grant them to me?

**Comment by dbu** [comment]
@frankdejonge saw the tweet. i can not give you more rights than i already did (i guess because dbu is a person and not an organization...). if i read https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization correctly, the normal workflow would be you put me into a group that is admin of thephpleague but has no rights on any of the existing repos. then i should be able to transfer. 

or simply create a new flysystem-phpcr repository and give me push right there, and i push the code without transferring the repo - there is no valuable history to preserve yet.

**Comment by frankdejonge** [comment]
@dbu I've invited you into the flysystem-phprc team, can you check if you can transfer the repo now?

**Comment by dbu** [comment]
yay!

i will see to wrap up https://github.com/thephpleague/flysystem/pull/402/ and then tag a release.

**Comment by frankdejonge** [comment]
Does this rely on the test PR?

**Comment by dbu** [comment]
no, for now it has a copy-paste test. but i want to wrap that up first to have a testing that makes sure this implementation is behaving correctly.
