### ISSUE TITLE
composer stability?

### ISSUE THREAD

**Issue by SignpostMarv** [thephpleague/flysystem-phpcr#5]
Currently doing some tinkering with a project, then noticed that this package gives a warning "Could not find package league/flysystem-phpcr for your minimum stability (stable)".

Is the package considered stable?

**Comment by dbu** [comment]
there are stable phpcr implementations, but the flysystem adapter has not
seen much real live testing as far as i know. then again it is not that
complicated, so i hope it works already ok nontheless.
i appreciate if you can try and give feedback. if it works well i am happy
to tag a stable version.

**Comment by liverbool** [comment]
@dbu got this error!

<img width="1069" alt="2560-09-24 11 31 28" src="https://user-images.githubusercontent.com/206804/30779468-f8137592-a11b-11e7-8ffb-8ffc7d72e9bd.png">
<img width="1059" alt="2560-09-24 11 36 55" src="https://user-images.githubusercontent.com/206804/30779490-d34a1bfc-a11c-11e7-87ae-9000d549d951.png">
<img width="1133" alt="2560-09-24 11 37 12" src="https://user-images.githubusercontent.com/206804/30779493-dacc4134-a11c-11e7-86fd-9d4e5c2161c4.png">
<img width="1069" alt="2560-09-24 11 37 27" src="https://user-images.githubusercontent.com/206804/30779494-dda57574-a11c-11e7-8e5b-d66eaf48d982.png">

**Comment by liverbool** [comment]
@dbu have you some idea?

**Comment by dbu** [comment]
hi, thanks for trying out this adapter.

if this is binary data, it should not be validated as a string, i think. can you try using the [BINARY](https://github.com/phpcr/phpcr/blob/db909970ca7449d69ccecd1912dedb857817eba7/src/PHPCR/PropertyType.php#L74) constant where we [write the data](https://github.com/thephpleague/flysystem-phpcr/blob/6287e4f10480bb23667136851893738d4ebc6fc1/src/PhpcrAdapter.php#L187)? and if that fixes it, do a pull request?

**Comment by liverbool** [comment]
Ok i'll try.

**Comment by liverbool** [comment]
@dbu everything seem work for me, live tested with simple file uploader and elFinder.

From my previous error i just change used `write` api to `writeStream` and everything work fine but we have small bug when create folder -- see #6 

Thanks

**Comment by dbu** [comment]
is your data in a stream or is it a string with binary data in it? if its a string, its more by accident that writeStream fixes it and we would still need to fix how we set the data in write().

**Comment by liverbool** [comment]
i've convert `SplFileInfo` to stream and then use `writeStream` to save it.

**Comment by dbu** [comment]
so you passed a SplFileInfo to the write method before? or did you read the file contents into a string and pass that to write? just trying to figure out if we need to fix something to prevent similar problems as you had.

**Comment by liverbool** [comment]
@dbu here my code snippet

https://github.com/phpmob/changmin/blob/b86dc7e40d1667b4518e40ce86af74084c76bb31/src/PhpMob/MediaBundle/Phpcr/DataUploader.php#L37-L59

**Comment by liverbool** [comment]
I never pass SplFileInfo to write so i thinks it can not.

**Comment by dbu** [comment]
the writeStream looks sane to me. but i am still trying to figure out what caused the problem you originally reported. do you still have that snipped by any chance?

**Comment by liverbool** [comment]
Here is default upload file (Sad to duplicate code dedicated to phpcr)

https://github.com/phpmob/changmin/blob/6013e77917d6f601e03107bbb1370274a07e5ba2/src/PhpMob/MediaBundle/Uploader/FileUploader.php#L59

**Comment by dbu** [comment]
thanks. okay, so you indeed pass a string with the binary data to `write`. which seems perfectly valid to do, so its a bug in this adapter. would you mind trying with the binary constant, as i described in https://github.com/thephpleague/flysystem-phpcr/issues/5#issuecomment-331792998 ? and do a fix PR if that helps? then you could also get rid of your duplicated code.

**Comment by liverbool** [comment]
Yes! as you said in https://github.com/thephpleague/flysystem-phpcr/issues/5#issuecomment-331792998 by using `BINARY` we have no error but i have no good idea to pass right type for content.

**Comment by dbu** [comment]
as this adapter is for files, i think we should just hardcode the BINARY in the setProperty call in the adapter. the property type of the phpcr data node is in the end binary anyways.

**Comment by liverbool** [comment]
I'm agree! fixed #7 and can stable?

**Comment by dbu** [comment]
thanks a lot! now that i know of somebody actually using this, i am happy to tag. just released 1.0.0

**Comment by liverbool** [comment]
@dbu Thanks for nice library 🎉
